version: '3'

services:
  flask-api:
    build:
      context: ./backend
      dockerfile: Dockerfile-flask
    image: qself
    ports:
      - "4000:8000"
    environment:
      - VIRTUAL_HOST=api.qself.soumyavaidya.me
      - LETSENCRYPT_HOST=api.qself.soumyavaidya.me
    network_mode: bridge

  vue-frontend:
    image: qself-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-vue
    environment:
      - VIRTUAL_HOST=qself.soumyavaidya.me
      - LETSENCRYPT_HOST=qself.soumyavaidya.me
    network_mode: bridge
    env_file:
      - .env
